!!python/object:argparse.Namespace
batch_size: 50
dim: 500
err_freq: 100
job_id: 587880
lambbda: 0.01
log_dir: ./exp
lr: 0.0001
method: adv
momentum: 0.0
optim: adam
perfect_model: false
pgd_eps: 0.01
pgd_itr: 100
radius: 1.3
seed: 0
total_itrs: 4000.0
total_samples: 50000000.0
